// Currency metadata for CurrNow.
// Curated entries have a proper symbol + brand colour; every other
// ISO code still gets a readable name and an auto-generated colour so
// the full API list (160+) can be displayed cleanly.

export type Currency = { code: string; name: string; symbol: string; color: string };

// A palette used to deterministically colour non-curated currencies.
const AUTO_COLORS = [
  '#3C7896', '#5A8C64', '#8C6432', '#7A5AA0', '#B4643C', '#46828C',
  '#8C4664', '#3C9650', '#5A64B4', '#B4503C', '#3C825A', '#967846',
  '#6E5AA0', '#3C82A0', '#A05A5A', '#4664A0', '#787850', '#C8783C',
];

export function autoColor(code: string): string {
  let h = 0;
  for (let i = 0; i < code.length; i++) h = (h * 31 + code.charCodeAt(i)) >>> 0;
  return AUTO_COLORS[h % AUTO_COLORS.length];
}

// Curated currencies (shown first, in this order).
export const CURATED: Currency[] = [
  { code: 'USD', name: 'US Dollar', symbol: '$', color: '#22786E' },
  { code: 'EUR', name: 'Euro', symbol: '€', color: '#2A5A96' },
  { code: 'GBP', name: 'British Pound', symbol: '£', color: '#783C96' },
  { code: 'JPY', name: 'Japanese Yen', symbol: '¥', color: '#BE465A' },
  { code: 'TRY', name: 'Turkish Lira', symbol: '₺', color: '#C88228' },
  { code: 'CHF', name: 'Swiss Franc', symbol: 'Fr', color: '#AA5A5A' },
  { code: 'CAD', name: 'Canadian Dollar', symbol: 'C$', color: '#3C8C78' },
  { code: 'AUD', name: 'Australian Dollar', symbol: 'A$', color: '#5A78A0' },
  { code: 'CNY', name: 'Chinese Yuan', symbol: '¥', color: '#C84646' },
  { code: 'HKD', name: 'Hong Kong Dollar', symbol: 'HK$', color: '#967846' },
  { code: 'SGD', name: 'Singapore Dollar', symbol: 'S$', color: '#46828C' },
  { code: 'SEK', name: 'Swedish Krona', symbol: 'kr', color: '#4664A0' },
  { code: 'NOK', name: 'Norwegian Krone', symbol: 'kr', color: '#8C4664' },
  { code: 'DKK', name: 'Danish Krone', symbol: 'kr', color: '#A05A5A' },
  { code: 'PLN', name: 'Polish Zloty', symbol: 'zł', color: '#7A6450' },
  { code: 'RUB', name: 'Russian Ruble', symbol: '₽', color: '#7A5AA0' },
  { code: 'INR', name: 'Indian Rupee', symbol: '₹', color: '#C8783C' },
  { code: 'BRL', name: 'Brazilian Real', symbol: 'R$', color: '#3C9650' },
  { code: 'MXN', name: 'Mexican Peso', symbol: '$', color: '#967832' },
  { code: 'ZAR', name: 'South African Rand', symbol: 'R', color: '#5A8C64' },
  { code: 'KRW', name: 'South Korean Won', symbol: '₩', color: '#5A6EBE' },
  { code: 'AED', name: 'UAE Dirham', symbol: 'د.إ', color: '#3C8C5A' },
  { code: 'SAR', name: 'Saudi Riyal', symbol: '﷼', color: '#3C7850' },
  { code: 'NZD', name: 'New Zealand Dollar', symbol: 'NZ$', color: '#3C7896' },
  { code: 'THB', name: 'Thai Baht', symbol: '฿', color: '#B4783C' },
  { code: 'IDR', name: 'Indonesian Rupiah', symbol: 'Rp', color: '#C85A46' },
  { code: 'MYR', name: 'Malaysian Ringgit', symbol: 'RM', color: '#468C78' },
  { code: 'PHP', name: 'Philippine Peso', symbol: '₱', color: '#3C82A0' },
  { code: 'VND', name: 'Vietnamese Dong', symbol: '₫', color: '#C8503C' },
  { code: 'CZK', name: 'Czech Koruna', symbol: 'Kč', color: '#6E5AA0' },
  { code: 'HUF', name: 'Hungarian Forint', symbol: 'Ft', color: '#8C6432' },
  { code: 'ILS', name: 'Israeli Shekel', symbol: '₪', color: '#3C6EA0' },
  { code: 'CLP', name: 'Chilean Peso', symbol: '$', color: '#B4503C' },
  { code: 'PKR', name: 'Pakistani Rupee', symbol: '₨', color: '#3C8250' },
  { code: 'EGP', name: 'Egyptian Pound', symbol: '£', color: '#B48232' },
  { code: 'NGN', name: 'Nigerian Naira', symbol: '₦', color: '#3C9646' },
  { code: 'UAH', name: 'Ukrainian Hryvnia', symbol: '₴', color: '#3C78B4' },
  { code: 'RON', name: 'Romanian Leu', symbol: 'lei', color: '#7A6E5A' },
  { code: 'COP', name: 'Colombian Peso', symbol: '$', color: '#C8963C' },
  { code: 'ARS', name: 'Argentine Peso', symbol: '$', color: '#5A82B4' },
  { code: 'QAR', name: 'Qatari Riyal', symbol: '﷼', color: '#7A2846' },
  { code: 'KWD', name: 'Kuwaiti Dinar', symbol: 'د.ك', color: '#3C825A' },
  { code: 'BHD', name: 'Bahraini Dinar', symbol: '.د.ب', color: '#8C3C46' },
  { code: 'OMR', name: 'Omani Rial', symbol: '﷼', color: '#5A3C6E' },
  { code: 'JOD', name: 'Jordanian Dinar', symbol: 'د.ا', color: '#8C5A3C' },
  { code: 'LKR', name: 'Sri Lankan Rupee', symbol: '₨', color: '#B4643C' },
  { code: 'BDT', name: 'Bangladeshi Taka', symbol: '৳', color: '#3C8C64' },
  { code: 'MAD', name: 'Moroccan Dirham', symbol: 'د.م.', color: '#B4503C' },
  { code: 'KES', name: 'Kenyan Shilling', symbol: 'Sh', color: '#3C8250' },
  { code: 'TWD', name: 'Taiwan Dollar', symbol: 'NT$', color: '#5A64B4' },
  { code: 'ISK', name: 'Icelandic Krona', symbol: 'kr', color: '#5A82A0' },
  { code: 'BGN', name: 'Bulgarian Lev', symbol: 'лв', color: '#787850' },
  { code: 'HRK', name: 'Croatian Kuna', symbol: 'kn', color: '#6E5AA0' },
  { code: 'DZD', name: 'Algerian Dinar', symbol: 'د.ج', color: '#8C6432' },
  { code: 'IQD', name: 'Iraqi Dinar', symbol: 'ع.د', color: '#7A463C' },
];

// ISO names for non-curated codes.
export const ISO_NAMES: Record<string, string> = {
  AFN: 'Afghan Afghani',
  ALL: 'Albanian Lek',
  AMD: 'Armenian Dram',
  ANG: 'Netherlands Antillean Guilder',
  AOA: 'Angolan Kwanza',
  AWG: 'Aruban Florin',
  AZN: 'Azerbaijani Manat',
  BAM: 'Bosnia-Herzegovina Mark',
  BBD: 'Barbadian Dollar',
  BIF: 'Burundian Franc',
  BMD: 'Bermudan Dollar',
  BND: 'Brunei Dollar',
  BOB: 'Bolivian Boliviano',
  BSD: 'Bahamian Dollar',
  BTN: 'Bhutanese Ngultrum',
  BWP: 'Botswanan Pula',
  BYN: 'Belarusian Ruble',
  BZD: 'Belize Dollar',
  CDF: 'Congolese Franc',
  CRC: 'Costa Rican Colon',
  CUP: 'Cuban Peso',
  CVE: 'Cape Verdean Escudo',
  DJF: 'Djiboutian Franc',
  DOP: 'Dominican Peso',
  ERN: 'Eritrean Nakfa',
  ETB: 'Ethiopian Birr',
  FJD: 'Fijian Dollar',
  FKP: 'Falkland Islands Pound',
  FOK: 'Faroese Krona',
  GEL: 'Georgian Lari',
  GGP: 'Guernsey Pound',
  GHS: 'Ghanaian Cedi',
  GIP: 'Gibraltar Pound',
  GMD: 'Gambian Dalasi',
  GNF: 'Guinean Franc',
  GTQ: 'Guatemalan Quetzal',
  GYD: 'Guyanaese Dollar',
  HNL: 'Honduran Lempira',
  HTG: 'Haitian Gourde',
  IMP: 'Isle of Man Pound',
  IRR: 'Iranian Rial',
  JEP: 'Jersey Pound',
  JMD: 'Jamaican Dollar',
  KGS: 'Kyrgystani Som',
  KHR: 'Cambodian Riel',
  KID: 'Kiribati Dollar',
  KMF: 'Comorian Franc',
  KYD: 'Cayman Islands Dollar',
  KZT: 'Kazakhstani Tenge',
  LAK: 'Laotian Kip',
  LBP: 'Lebanese Pound',
  LRD: 'Liberian Dollar',
  LSL: 'Lesotho Loti',
  LYD: 'Libyan Dinar',
  MDL: 'Moldovan Leu',
  MGA: 'Malagasy Ariary',
  MKD: 'Macedonian Denar',
  MMK: 'Myanmar Kyat',
  MNT: 'Mongolian Tugrik',
  MOP: 'Macanese Pataca',
  MRU: 'Mauritanian Ouguiya',
  MUR: 'Mauritian Rupee',
  MVR: 'Maldivian Rufiyaa',
  MWK: 'Malawian Kwacha',
  MZN: 'Mozambican Metical',
  NAD: 'Namibian Dollar',
  NIO: 'Nicaraguan Cordoba',
  NPR: 'Nepalese Rupee',
  PAB: 'Panamanian Balboa',
  PEN: 'Peruvian Sol',
  PGK: 'Papua New Guinean Kina',
  PYG: 'Paraguayan Guarani',
  RSD: 'Serbian Dinar',
  RWF: 'Rwandan Franc',
  SBD: 'Solomon Islands Dollar',
  SCR: 'Seychellois Rupee',
  SDG: 'Sudanese Pound',
  SHP: 'Saint Helena Pound',
  SLE: 'Sierra Leonean Leone',
  SLL: 'Sierra Leonean Leone',
  SOS: 'Somali Shilling',
  SRD: 'Surinamese Dollar',
  SSP: 'South Sudanese Pound',
  STN: 'Sao Tome Dobra',
  SYP: 'Syrian Pound',
  SZL: 'Swazi Lilangeni',
  TJS: 'Tajikistani Somoni',
  TMT: 'Turkmenistani Manat',
  TND: 'Tunisian Dinar',
  TOP: 'Tongan Paanga',
  TTD: 'Trinidad & Tobago Dollar',
  TVD: 'Tuvaluan Dollar',
  TZS: 'Tanzanian Shilling',
  UGX: 'Ugandan Shilling',
  UYU: 'Uruguayan Peso',
  UZS: 'Uzbekistani Som',
  VES: 'Venezuelan Bolivar',
  VUV: 'Vanuatu Vatu',
  WST: 'Samoan Tala',
  XAF: 'Central African CFA Franc',
  XCD: 'East Caribbean Dollar',
  XDR: 'Special Drawing Rights',
  XOF: 'West African CFA Franc',
  XPF: 'CFP Franc',
  YER: 'Yemeni Rial',
  ZMW: 'Zambian Kwacha',
  ZWL: 'Zimbabwean Dollar',
};

const CURATED_CODES = new Set(CURATED.map((c) => c.code));

// Build the full list from the API's rate keys: curated first (nice),
// then everything else alphabetically with a readable name + auto colour.
export function buildCurrencyList(rateCodes: string[]): Currency[] {
  const extras: Currency[] = rateCodes
    .filter((code) => !CURATED_CODES.has(code))
    .sort()
    .map((code) => ({
      code,
      name: ISO_NAMES[code] || code,
      symbol: code.slice(0, 2),
      color: autoColor(code),
    }));
  return [...CURATED, ...extras];
}
